In [111]:
import numpy as np
x=[115.3, 195.5, 120.5, 110.2, 90.4, 105.6, 110.9, 116.3, 122.3, 125.4,90.4]

In [112]:
mean = sum(x) / len(x)

In [113]:
mean

118.43636363636365

In [114]:
import statistics

In [115]:
print(statistics.mean(x))

118.43636363636364


In [116]:
x.sort()
# x = np.sort(x)


In [117]:
x

[90.4, 90.4, 105.6, 110.2, 110.9, 115.3, 116.3, 120.5, 122.3, 125.4, 195.5]

In [118]:
n=len(x)
n

11

In [119]:
if  n% 2 == 0:
    median1 = x[n//2]
    median2 = x[n//2 - 1]
    median = (median1 + median2)/2
else:
    median = x[n//2]
print("Median is: " + str(median))

Median is: 115.3


In [120]:
# print(statistics.median(x))
np.median(x)

115.3

In [121]:
frequency = {}
for value in x:
        frequency[value] = frequency.get(value, 0) + 1

In [122]:
frequency

{90.4: 2,
 105.6: 1,
 110.2: 1,
 110.9: 1,
 115.3: 1,
 116.3: 1,
 120.5: 1,
 122.3: 1,
 125.4: 1,
 195.5: 1}

In [123]:
frequencs=list(frequency.values())
print(frequencs)

[2, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [124]:
most_frequent = np.max(frequencs)

In [125]:
most_frequent

2

In [126]:
modes = [key for key, value in frequency.items()
                      if value == most_frequent]

In [127]:
modes

[90.4]

In [128]:
freq = {}
for key in x:
    freq[key] = freq.get(key, 0) + 1

freqencs = list(freq.values())

maxfr = np.max(freqencs)

def mmm():
    for i in range(len(x)):
        if maxfr == freqencs[i]:
            return x[i]

mode = mmm()
mode

90.4

In [129]:
print(statistics.mode(x))

90.4


In [130]:
variance = sum((i - mean) ** 2 for i in x) / (n-1)

In [131]:
variance

788.2365454545454

In [132]:
print(statistics.variance(x))

788.2365454545454


In [133]:
standarddev= variance ** 0.5

In [134]:
standarddev

28.07555067054866

In [135]:
print(statistics.stdev(x))

28.07555067054866


In [136]:
import numpy as np
max = np.max(x)
min = np.min(x)


In [137]:
scaled_arr = list((i - min) / (max - min) for i in x)

In [138]:
print(scaled_arr)

[0.0, 0.0, 0.14462416745956222, 0.18839200761179828, 0.1950523311132255, 0.23691722169362506, 0.24643196955280677, 0.2863939105613701, 0.3035204567078972, 0.3330161750713606, 1.0]


In [139]:
x=[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [140]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# transform data
scaled = scaler.fit_transform(x)
print(scaled)

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


In [141]:
X=[115.3, 195.5, 120.5, 110.2, 90.4, 105.6, 110.9, 116.3, 122.3, 125.4,90.4]
for i in range(len(X)):
        X[i] = (X[i] - statistics.mean(X)) /(statistics.stdev(X))


In [142]:
X=[115.3, 195.5, 120.5, 110.2, 90.4, 105.6, 110.9, 116.3, 122.3, 125.4,90.4]

In [143]:
stand_arr = np.array([(i -statistics.mean(X) ) / (statistics.stdev(X)) for i in X])

In [144]:
stand_arr

array([-0.11171156,  2.74486642,  0.07350297, -0.29336428, -0.99860423,
       -0.4572079 , -0.26843155, -0.07609338,  0.13761569,  0.24803205,
       -0.99860423])

In [145]:
print(round(statistics.mean(stand_arr),2))

-0.0


In [146]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler
# define data
data = asarray([[100, 0.001],
[8, 0.05],
[50, 0.005],
[88, 0.07],
[4, 0.1]])
print(data)
# define standard scaler
scaler = StandardScaler()
# transform 

scaled = scaler.fit_transform(data)
print(scaled)

[[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]
[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]


In [147]:
print(round(np.mean(scaled),5))

-0.0


In [148]:
print(np.std(scaled))

1.0
