In [27]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np
import pandas as pd
data=pd.read_csv("datasets\glass(SVM Program).csv")
data.head()
x=data.drop("Type",axis=1)
y=data.Type

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [29]:
linear=svm.SVC(kernel="linear")
linear.fit(x_train,y_train)

print(linear.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [7.50000e+01 1.51596e+00 1.30200e+01 3.56000e+00 1.54000e+00 7.31100e+01
  7.20000e-01 7.90000e+00 0.00000e+00 0.00000e+00]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.66000e+02 1.52171e+00 1.15600e+01 1.88000e+00 1.56000e+00 7.28600e+01
  4.70000e-01 1.14100e+01 0.00000e+00 0.00000e+00]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]
 [1.64000e+02 1.51514e+00 1.40100e+01 2.68000e+00 3.50000e+00 6.98900e+01
  1.68000e+00 5.87000e+00 2.20000e+00 0.00000e+00]


In [30]:
print(linear.n_support_)
y_pred=linear.predict(x_test)

[1 2 2 3 3 3]


In [31]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9692307692307692


In [32]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[22  0  0  0  0  0]
 [ 2 21  0  0  0  0]
 [ 0  0  4  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0 10]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.92      1.00      0.96        22
           2       1.00      0.91      0.95        23
           3       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         4
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00        10

    accuracy                           0.97        65
   macro avg       0.99      0.99      0.99        65
weighted avg       0.97      0.97      0.97        65



In [34]:
model1=SVC(kernel='sigmoid',gamma=0.76)
model2=SVC(kernel='poly',degree=3)
model3=SVC(kernel='rbf')

In [35]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [36]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [37]:
print("prediction by model1",accuracy_score(y_test,y_pred1))
print("prediction by model2",accuracy_score(y_test,y_pred2))
print("prediction by model3",accuracy_score(y_test,y_pred3))

prediction by model1 0.35384615384615387
prediction by model2 0.9076923076923077
prediction by model3 0.8153846153846154


In [38]:
print("Sigmoid:\n"+classification_report(y_test,y_pred1))
print("Polynomial:\n"+classification_report(y_test,y_pred2))
print("RBF:\n"+classification_report(y_test,y_pred3))

Sigmoid:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        22
           2       0.35      1.00      0.52        23
           3       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00        10

    accuracy                           0.35        65
   macro avg       0.06      0.17      0.09        65
weighted avg       0.13      0.35      0.18        65

Polynomial:
              precision    recall  f1-score   support

           1       0.81      1.00      0.90        22
           2       1.00      0.78      0.88        23
           3       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         4
           6       0.67      1.00      0.80         2
           7       1.00      0.90      0.95        10

    accuracy                           0.91        65
  

C:\Users\LOHITH\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\LOHITH\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\LOHITH\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu